[package]
name = "trendt-torrent"
version = "0.1.0"
edition = "2024"

[dependencies]
trendt-bencode = { path = "../trendt-bencode" }
serde = { version = "1", features = ["derive"] }
serde_bytes = "0.11.19"
