[package]
name = "trendt-core"
version = "0.1.0"
edition = "2024"

[dependencies]
trendt-torrent = { path = "../trendt-torrent/" }
trendt-tracker = { path = "../trendt-tracker" }
trendt-peer = { path = "../trendt-peer" }
